status: true
dependencies:
  config:
    - field.storage.lms_activity.phrase_feedback
    - lms.lms_activity_type._bundle_placeholder_
  module:
    - lms_answer_plugins
id: lms_activity._bundle_placeholder_.phrase_feedback
field_name: phrase_feedback
entity_type: lms_activity
bundle: _bundle_placeholder_
label: 'Phrase-based Feedback'
description: 'Define phrases to search for in student answers, and give feedback based on whether they are present or absent.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: lms_phrase_feedback