status: true
dependencies:
  config:
    - field.storage.lms_activity.field_distraction_words
    - lms.lms_activity_type._bundle_placeholder_
id: lms_activity._bundle_placeholder_.field_distraction_words
field_name: field_distraction_words
entity_type: lms_activity
bundle: _bundle_placeholder_
label: 'Distraction Words'
description: 'Add any incorrect words you want to include in the available choices. These will be mixed with the correct answers.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
