<?php

/**
 * @file
 * Contains legacy hooks.
 */

declare(strict_types=1);

use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\lms\Entity\AnswerInterface;
use Drupal\lms_answer_comments\Hook\AnswerCommentsHooks;

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function lms_answer_comments_entity_base_field_info(EntityTypeInterface $entity_type): array {
  return \Drupal::service(AnswerCommentsHooks::class)->entityBaseFieldInfo($entity_type);
}

/**
 * Implements hook_entity_base_field_info().
 */
#[LegacyHook]
function lms_answer_comments_lms_answer_details_alter(array &$build, AnswerInterface $answer, CacheableMetadata $cacheability): void {
  \Drupal::service(AnswerCommentsHooks::class)->lmsAnswerDetailsAlter($build, $answer, $cacheability);
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
#[LegacyHook]
function lms_answer_comments_form_lms_answer_evaluate_form_alter(array &$form, FormStateInterface $form_state): void {
  \Drupal::service(AnswerCommentsHooks::class)->answerEvaluateFormAlter($form, $form_state);
}
